name: Auto Like Tweets
on:
  schedule:
    - cron: '0 10 * * *' # Щодня о 10:00 UTC (12:00 за Києвом, EEST)
  workflow_dispatch: # Дозволяє запускати вручну
jobs:
  like-tweets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          MAX_LIKES_PER_DAY: ${{ secrets.MAX_LIKES_PER_DAY }}
          SEARCH_QUERY: ${{ secrets.SEARCH_QUERY }}
        run: python auto_like.py
